Fix key expire function
The key expire function failed with

RuntimeError: dictionary changed size during iteration

Python 3 did not act on a copy while iterating over a dictionary any
more. Instead a iterator is used. Removing elements from the dictionary
will fail and throw the given exception.

Iterate over a copy of the dictionary.

Signed-off-by: Benedikt Spranger <bene@eurovibes.org>